-- ============================================================
--  Shramic Agri Tech Platform — MySQL Database Schema
--  Run: mysql -u root -p < schema.sql
-- ============================================================

CREATE DATABASE IF NOT EXISTS shramic_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE shramic_db;

-- Users (farmers & workers)
CREATE TABLE IF NOT EXISTS users (
  id          INT AUTO_INCREMENT PRIMARY KEY,
  name        VARCHAR(100) NOT NULL,
  email       VARCHAR(150) NOT NULL UNIQUE,
  password    VARCHAR(255) NOT NULL,
  role        ENUM('farmer','worker','admin') DEFAULT 'farmer',
  phone       VARCHAR(20),
  location    VARCHAR(200),
  state       VARCHAR(100),
  avatar_url  VARCHAR(500),
  is_active   BOOLEAN DEFAULT TRUE,
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Worker profiles
CREATE TABLE IF NOT EXISTS worker_profiles (
  id                INT AUTO_INCREMENT PRIMARY KEY,
  user_id           INT NOT NULL UNIQUE,
  skills            JSON,               -- ["sowing","harvesting","irrigation"]
  experience_years  INT DEFAULT 0,
  preferred_state   VARCHAR(100),
  preferred_district VARCHAR(100),
  daily_wage        DECIMAL(10,2),
  is_available      BOOLEAN DEFAULT TRUE,
  lat               DECIMAL(10, 7),
  lng               DECIMAL(10, 7),
  rating            DECIMAL(3,2) DEFAULT 0,
  total_jobs        INT DEFAULT 0,
  bio               TEXT,
  created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Jobs posted by farmers
CREATE TABLE IF NOT EXISTS jobs (
  id            INT AUTO_INCREMENT PRIMARY KEY,
  farmer_id     INT NOT NULL,
  title         VARCHAR(200) NOT NULL,
  description   TEXT,
  job_type      ENUM('sowing','harvesting','irrigation','spraying','ploughing','other') NOT NULL,
  location      VARCHAR(200),
  state         VARCHAR(100),
  district      VARCHAR(100),
  wage_per_day  DECIMAL(10,2),
  workers_needed INT DEFAULT 1,
  start_date    DATE,
  end_date      DATE,
  status        ENUM('open','in_progress','completed','cancelled') DEFAULT 'open',
  lat           DECIMAL(10,7),
  lng           DECIMAL(10,7),
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (farmer_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Job applications by workers
CREATE TABLE IF NOT EXISTS job_applications (
  id          INT AUTO_INCREMENT PRIMARY KEY,
  job_id      INT NOT NULL,
  worker_id   INT NOT NULL,
  status      ENUM('pending','accepted','rejected','withdrawn') DEFAULT 'pending',
  cover_note  TEXT,
  applied_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (job_id)    REFERENCES jobs(id)  ON DELETE CASCADE,
  FOREIGN KEY (worker_id) REFERENCES users(id) ON DELETE CASCADE,
  UNIQUE KEY uq_application (job_id, worker_id)
);

-- Equipment listings
CREATE TABLE IF NOT EXISTS equipment (
  id            INT AUTO_INCREMENT PRIMARY KEY,
  owner_id      INT NOT NULL,
  name          VARCHAR(150) NOT NULL,
  type          ENUM('tractor','harvester','rotavator','sprayer','thresher','other') NOT NULL,
  description   TEXT,
  rent_per_day  DECIMAL(10,2),
  location      VARCHAR(200),
  state         VARCHAR(100),
  is_available  BOOLEAN DEFAULT TRUE,
  image_url     VARCHAR(500),
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Equipment bookings
CREATE TABLE IF NOT EXISTS bookings (
  id            INT AUTO_INCREMENT PRIMARY KEY,
  equipment_id  INT NOT NULL,
  farmer_id     INT NOT NULL,
  start_date    DATE NOT NULL,
  end_date      DATE NOT NULL,
  total_amount  DECIMAL(10,2),
  status        ENUM('pending','confirmed','cancelled','completed') DEFAULT 'pending',
  notes         TEXT,
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (equipment_id) REFERENCES equipment(id) ON DELETE CASCADE,
  FOREIGN KEY (farmer_id)    REFERENCES users(id)     ON DELETE CASCADE
);

-- Marketplace listings (seeds, fertilizers, nurseries)
CREATE TABLE IF NOT EXISTS marketplace (
  id           INT AUTO_INCREMENT PRIMARY KEY,
  seller_id    INT NOT NULL,
  title        VARCHAR(200) NOT NULL,
  category     ENUM('seeds','fertilizer','pesticide','nursery','tools','other') NOT NULL,
  description  TEXT,
  price        DECIMAL(10,2),
  unit         VARCHAR(50),
  stock        INT DEFAULT 0,
  image_url    VARCHAR(500),
  state        VARCHAR(100),
  contact      VARCHAR(100),
  created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (seller_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Soil / Yield reports generated by AI
CREATE TABLE IF NOT EXISTS soil_reports (
  id               INT AUTO_INCREMENT PRIMARY KEY,
  user_id          INT NOT NULL,
  crop             VARCHAR(100),
  season           VARCHAR(50),
  state            VARCHAR(100),
  area             DECIMAL(10,2),
  fertilizer_used  DECIMAL(10,2),
  pesticide_used   DECIMAL(10,2),
  predicted_yield  DECIMAL(10,4),
  recommendation   TEXT,
  created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Crop AI recommendations
CREATE TABLE IF NOT EXISTS crop_recommendations (
  id               INT AUTO_INCREMENT PRIMARY KEY,
  user_id          INT NOT NULL,
  nitrogen         DECIMAL(8,2),
  phosphorus       DECIMAL(8,2),
  potassium        DECIMAL(8,2),
  temperature      DECIMAL(6,2),
  humidity         DECIMAL(6,2),
  ph               DECIMAL(5,2),
  rainfall         DECIMAL(8,2),
  recommended_crop VARCHAR(100),
  confidence       DECIMAL(5,2),
  created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Payments (mock)
CREATE TABLE IF NOT EXISTS payments (
  id               INT AUTO_INCREMENT PRIMARY KEY,
  payer_id         INT NOT NULL,
  receiver_id      INT,
  amount           DECIMAL(10,2) NOT NULL,
  type             ENUM('worker_wage','equipment_booking','consultation','marketplace') NOT NULL,
  reference_id     INT,           -- job_id / booking_id / etc.
  status           ENUM('pending','success','failed','refunded') DEFAULT 'pending',
  payment_method   VARCHAR(50) DEFAULT 'mock_upi',
  transaction_id   VARCHAR(100),
  created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (payer_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Reviews
CREATE TABLE IF NOT EXISTS reviews (
  id           INT AUTO_INCREMENT PRIMARY KEY,
  reviewer_id  INT NOT NULL,
  reviewee_id  INT NOT NULL,
  job_id       INT,
  rating       TINYINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment      TEXT,
  created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (reviewer_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (reviewee_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Agriculture calendar events
CREATE TABLE IF NOT EXISTS calendar_events (
  id           INT AUTO_INCREMENT PRIMARY KEY,
  user_id      INT NOT NULL,
  title        VARCHAR(200) NOT NULL,
  event_type   ENUM('sowing','irrigation','fertilizer','harvest','spraying','other') NOT NULL,
  event_date   DATE NOT NULL,
  notes        TEXT,
  is_recurring BOOLEAN DEFAULT FALSE,
  created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Community posts / tips
CREATE TABLE IF NOT EXISTS community_posts (
  id          INT AUTO_INCREMENT PRIMARY KEY,
  user_id     INT NOT NULL,
  title       VARCHAR(300) NOT NULL,
  content     TEXT,
  video_url   VARCHAR(500),
  category    ENUM('tip','disease','scheme','market','general') DEFAULT 'general',
  likes       INT DEFAULT 0,
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Government schemes (static seed data)
CREATE TABLE IF NOT EXISTS schemes (
  id          INT AUTO_INCREMENT PRIMARY KEY,
  name        VARCHAR(300) NOT NULL,
  description TEXT,
  ministry    VARCHAR(200),
  benefit     VARCHAR(300),
  deadline    DATE,
  link        VARCHAR(500),
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Seed data: schemes
INSERT INTO schemes (name, description, ministry, benefit, link) VALUES
('PM-KISAN', 'Income support of ₹6000/year to farmer families', 'Ministry of Agriculture', '₹6000 per year', 'https://pmkisan.gov.in'),
('Pradhan Mantri Fasal Bima Yojana', 'Crop insurance against natural calamities', 'Ministry of Agriculture', 'Crop loss compensation', 'https://pmfby.gov.in'),
('Kisan Credit Card', 'Short-term credit for agricultural needs', 'NABARD', 'Low interest credit up to ₹3 lakh', 'https://www.nabard.org'),
('Soil Health Card Scheme', 'Free soil testing and fertilizer recommendations', 'Ministry of Agriculture', 'Free soil health card', 'https://soilhealth.dac.gov.in'),
('PM Kisan Maandhan Yojana', 'Pension scheme for small farmers', 'Ministry of Agriculture', '₹3000/month pension after 60', 'https://maandhan.in'),
('PMEGP', 'Credit-linked subsidy for agri-entrepreneurs', 'MSME Ministry', '15-35% subsidy on project cost', 'https://www.kviconline.gov.in');

-- Seed admin user (password: Admin@123 bcrypt hash)
INSERT INTO users (name, email, password, role, location) VALUES
('Admin', 'admin@shramic.in', '$2b$10$X7UrH1QnLc3hpMK2yCbZsusAZ5MkRAiEL8MCajX0mV5fKkuT8e4Oa', 'admin', 'New Delhi, India');
