import { createContext, useContext, useEffect, useState } from 'react'

// ── Full translations for every string in the app ──────────────────────────────
const T = {
  en: {
    // Nav
    dashboard:'Dashboard', jobs:'Jobs', workers:'Workers', live_tracking:'Live Tracking',
    equipment:'Equipment', marketplace:'Marketplace', ai_advisory:'AI Advisory',
    calendar:'Calendar', schemes:'Schemes', market_prices:'Market Prices',
    community:'Community', payments:'Payments', profile:'Profile', sign_out:'Sign Out',

    // Greetings
    good_morning:'Good morning', good_afternoon:'Good afternoon', good_evening:'Good evening',
    farmer:'Farmer', worker:'Worker', admin:'Admin',

    // Dashboard
    open_jobs:'Open Jobs', available_workers:'Available Workers', platform_overview:'Platform at a glance',
    live_numbers:'Live numbers across India', quick_access:'Quick Access',
    recent_jobs:'Recent Jobs', farm_schedule:'Farm Schedule', community_posts:'Community',
    view_all:'View all', add_event:'+ Add Event', share_tip:'Share a tip',
    no_jobs:'No open jobs', no_events:'No events yet', no_posts:'No posts yet',
    schedule_now:'Schedule now', total_spent:'Total Spent', jobs_posted:'Jobs Posted',
    applications:'Applications', equipment_booked:'Equipment Booked',
    jobs_applied:'Jobs Applied', accepted:'Accepted', earned:'Earned', rating:'Rating',
    live_weather:'Live Weather', todays_farm_advisory:"Today's Farm Advisory",
    day_forecast:'5-Day Forecast', seed_prices:'Seed & Commodity Prices',
    india_msp:'India MSP', global:'Global', feels_like:'Feels like',
    humidity:'Humidity', wind:'Wind', rain:'Rain',

    // Jobs page
    post_job:'Post Job', apply_now:'Apply Now', job_type:'Job Type', all_types:'All Types',
    all_states:'All States', open_jobs_tab:'Open Jobs', in_progress:'In Progress',
    completed:'Completed', search_jobs:'Search jobs…', workers_needed:'Workers Needed',
    wage_per_day:'Wage per day (₹)', start_date:'Start Date', end_date:'End Date',
    description:'Description', location:'Location', state:'State', season:'Season',
    job_title:'Job Title', post_job_btn:'Post Job', cancel:'Cancel', posting:'Posting…',
    days_left:'d left', last_day:'Last day', ai_wage:'AI Fair Wage Suggestion',
    wage_range:'Range', loading_jobs:'Loading jobs…', no_jobs_found:'No jobs found',

    // Workers
    available:'Available', unavailable:'Unavailable', contact:'Contact',
    exp_years:'yrs exp', all_workers:'All workers', available_only:'Available only',
    all_skills:'All Skills', my_profile:'My Worker Profile', save_profile:'Save Profile',
    skills:'Skills', experience:'Experience (years)', preferred_state:'Preferred State',
    daily_wage:'Daily Wage (₹)', bio:'Bio', saving:'Saving…', any_state:'Any state',
    availability_status:'Availability Status',

    // Equipment
    list_equipment:'List Equipment', book:'Book', all_types_eq:'All Types',
    rent_per_day:'Rent/day (₹)', equipment_name:'Equipment Name', type:'Type',
    my_bookings:'My Bookings', confirm_booking:'Confirm Booking',
    start:'Start Date', end:'End Date', notes:'Notes', total:'Total',
    days:'day(s)', booking_success:'Booked successfully',

    // Marketplace
    add_listing:'+ Add Listing', all_categories:'All Categories',
    title:'Title', category:'Category', price:'Price', unit:'Unit',
    stock:'Stock', contact_seller:'Contact', seller:'Seller',

    // AI
    crop_recommendation:'Crop Recommendation', disease_detection:'Disease Detection',
    soil_yield:'Soil & Yield', get_recommendation:'Get Crop Recommendation',
    analysing:'Analysing…', recommended_crop:'Recommended Crop',
    confidence:'confidence', alternatives:'Alternatives',
    upload_photo:'Click to upload a plant leaf photo',
    detect_disease:'Detect Disease & Get Treatment',
    detecting:'Detecting…', what_is_this:'What is this disease?',
    do_now:'Do This RIGHT NOW', step_by_step:'Step-by-Step Treatment Plan',
    recommended_products:'Recommended Products', prevention:'Prevention Next Season',
    need_help:'Need more help?', kisan_helpline:'Kisan Call Centre',
    predicted_yield:'Predicted Yield', total_production:'Total Production',
    crop_duration:'Crop Duration (days)', soil_profile:'Soil Profile',
    fertilizer_rec:'Fertilizer Recommendation', application_schedule:'Application Schedule',
    companion_crops:'Companion Crops', harvest_tips:'Harvest Tips',
    get_analysis:'Get Complete Soil & Yield Analysis',

    // Calendar
    add_event_title:'Add Farm Event', event_type:'Event Type', event_title:'Event Title',
    date:'Date', upcoming_events:'Upcoming Events', by_type:'By Type',
    month_tips:'Tips', calendar_view:'Calendar', list_view:'List',
    today:'Today', tomorrow:'Tomorrow', click_date:'Click any date to add an event',
    total_events:'Total Events', upcoming:'Upcoming', done_events:'Completed',
    next_event:'Next Event',

    // Community
    search_posts:'Search posts…', newest_first:'Newest first', most_liked:'Most liked',
    share_post:'+ Share Post', write_post:'Write a Post', share_knowledge:'Share Your Knowledge',
    trending:'Trending Topics', quick_knowledge:'Quick Knowledge',
    post_title:'Title', your_message:'Your tip / message', video_link:'Video Link (optional)',
    publishing:'Posting…', publish:'Share Post', char_count:'characters',
    farming_tip:'Farming Tip', disease_alert:'Disease Alert', govt_scheme:'Govt Scheme',
    market_update:'Market Update', general:'General', all_posts:'All',
    no_posts_found:'No posts match your search.',

    // Schemes
    apply:'Apply →',

    // Payments
    no_transactions:'No transactions yet', recent_transactions:'Recent Transactions',
    amount:'Amount', status:'Status', tx_date:'Date', tx_type:'Type',

    // Profile
    personal_info:'Personal Information', full_name:'Full Name', phone:'Phone Number',
    village:'Village / Location', save_changes:'Save Changes', saved_ok:'✓ Profile saved!',
    worker_profile:'Worker Profile', language_voice:'Language & Voice',
    activity:'Activity', interface_language:'Interface Language', active:'Active',
    voice_input:'Voice Input', text_to_speech:'Text to Speech', play_sample:'Play sample',
    member_since:'Member since',
  },

  hi: {
    dashboard:'डैशबोर्ड', jobs:'काम', workers:'मजदूर', live_tracking:'लाइव ट्रैकिंग',
    equipment:'उपकरण', marketplace:'बाज़ार', ai_advisory:'AI सलाह',
    calendar:'कैलेंडर', schemes:'योजनाएं', market_prices:'बाज़ार भाव',
    community:'समुदाय', payments:'भुगतान', profile:'प्रोफ़ाइल', sign_out:'साइन आउट',
    good_morning:'सुप्रभात', good_afternoon:'नमस्ते', good_evening:'शुभ संध्या',
    farmer:'किसान', worker:'मजदूर', admin:'व्यवस्थापक',
    open_jobs:'खुले काम', available_workers:'उपलब्ध मजदूर', platform_overview:'मंच पर एक नज़र',
    live_numbers:'भारत भर के लाइव नंबर', quick_access:'त्वरित पहुँच',
    recent_jobs:'हाल के काम', farm_schedule:'खेत कार्यक्रम', community_posts:'समुदाय',
    view_all:'सभी देखें', add_event:'+ घटना जोड़ें', share_tip:'सुझाव साझा करें',
    no_jobs:'कोई खुला काम नहीं', no_events:'अभी कोई कार्यक्रम नहीं', no_posts:'अभी कोई पोस्ट नहीं',
    schedule_now:'अभी शेड्यूल करें', total_spent:'कुल खर्च', jobs_posted:'काम पोस्ट',
    applications:'आवेदन', equipment_booked:'उपकरण बुक', jobs_applied:'काम के लिए आवेदन',
    accepted:'स्वीकृत', earned:'कमाई', rating:'रेटिंग',
    live_weather:'लाइव मौसम', todays_farm_advisory:'आज की खेती सलाह',
    day_forecast:'5 दिन का पूर्वानुमान', seed_prices:'बीज और कमोडिटी मूल्य',
    india_msp:'भारत MSP', global:'वैश्विक', feels_like:'महसूस होता है',
    humidity:'आर्द्रता', wind:'हवा', rain:'बारिश',
    post_job:'काम पोस्ट करें', apply_now:'अभी आवेदन करें', job_type:'काम का प्रकार',
    all_types:'सभी प्रकार', all_states:'सभी राज्य', open_jobs_tab:'खुले काम',
    in_progress:'प्रगति में', completed:'पूरा हुआ', search_jobs:'काम खोजें…',
    workers_needed:'जरूरी मजदूर', wage_per_day:'प्रतिदिन वेतन (₹)',
    start_date:'शुरू तारीख', end_date:'अंत तारीख', description:'विवरण',
    location:'स्थान', state:'राज्य', season:'मौसम', job_title:'काम का शीर्षक',
    post_job_btn:'काम पोस्ट करें', cancel:'रद्द करें', posting:'पोस्ट हो रहा है…',
    days_left:'दिन बचे', last_day:'आखिरी दिन', ai_wage:'AI उचित वेतन सुझाव',
    wage_range:'सीमा', loading_jobs:'काम लोड हो रहे हैं…', no_jobs_found:'कोई काम नहीं मिला',
    available:'उपलब्ध', unavailable:'अनुपलब्ध', contact:'संपर्क',
    exp_years:'वर्ष अनुभव', all_workers:'सभी मजदूर', available_only:'केवल उपलब्ध',
    all_skills:'सभी कौशल', my_profile:'मेरी प्रोफ़ाइल', save_profile:'प्रोफ़ाइल सहेजें',
    skills:'कौशल', experience:'अनुभव (वर्ष)', preferred_state:'पसंदीदा राज्य',
    daily_wage:'प्रतिदिन वेतन (₹)', bio:'परिचय', saving:'सहेजा जा रहा है…', any_state:'कोई भी राज्य',
    availability_status:'उपलब्धता स्थिति',
    list_equipment:'उपकरण सूचीबद्ध करें', book:'बुक करें',
    add_listing:'+ सूची जोड़ें', title:'शीर्षक', category:'श्रेणी', price:'मूल्य',
    crop_recommendation:'फसल सिफारिश', disease_detection:'रोग पहचान',
    soil_yield:'मिट्टी और उत्पादन', get_recommendation:'फसल सिफारिश पाएं',
    recommended_crop:'अनुशंसित फसल', confidence:'विश्वास', alternatives:'विकल्प',
    upload_photo:'पौधे की पत्ती की तस्वीर अपलोड करें', detect_disease:'रोग पहचानें',
    detecting:'पहचान हो रही है…', what_is_this:'यह रोग क्या है?',
    do_now:'अभी यह करें', step_by_step:'चरण-दर-चरण उपचार',
    recommended_products:'अनुशंसित उत्पाद', prevention:'अगले मौसम की रोकथाम',
    predicted_yield:'अनुमानित उत्पादन', total_production:'कुल उत्पादन',
    soil_profile:'मिट्टी प्रोफ़ाइल', fertilizer_rec:'उर्वरक सिफारिश',
    application_schedule:'उर्वरक कार्यक्रम', companion_crops:'सहयोगी फसलें',
    harvest_tips:'कटाई सुझाव', get_analysis:'मिट्टी और उत्पादन विश्लेषण पाएं',
    add_event_title:'खेत घटना जोड़ें', event_type:'घटना प्रकार', event_title:'घटना शीर्षक',
    date:'तारीख', upcoming_events:'आगामी घटनाएं', by_type:'प्रकार के अनुसार',
    calendar_view:'कैलेंडर', list_view:'सूची', today:'आज', tomorrow:'कल',
    click_date:'तारीख पर क्लिक करें', total_events:'कुल घटनाएं',
    upcoming:'आगामी', done_events:'पूर्ण', next_event:'अगली घटना',
    search_posts:'पोस्ट खोजें…', newest_first:'नवीनतम पहले', most_liked:'सबसे पसंदीदा',
    share_post:'+ पोस्ट साझा करें', write_post:'पोस्ट लिखें',
    share_knowledge:'अपना ज्ञान साझा करें', trending:'ट्रेंडिंग विषय',
    post_title:'शीर्षक', your_message:'आपका सुझाव', video_link:'वीडियो लिंक (वैकल्पिक)',
    publishing:'पोस्ट हो रहा है…', publish:'पोस्ट करें',
    farming_tip:'खेती सुझाव', disease_alert:'रोग चेतावनी',
    govt_scheme:'सरकारी योजना', market_update:'बाज़ार अपडेट', general:'सामान्य',
    all_posts:'सभी', no_posts_found:'कोई पोस्ट नहीं मिली।', apply:'आवेदन करें →',
    no_transactions:'कोई लेनदेन नहीं', recent_transactions:'हाल के लेनदेन',
    amount:'राशि', status:'स्थिति', tx_date:'तारीख', tx_type:'प्रकार',
    personal_info:'व्यक्तिगत जानकारी', full_name:'पूरा नाम', phone:'फोन नंबर',
    village:'गाँव / स्थान', save_changes:'बदलाव सहेजें', saved_ok:'✓ प्रोफ़ाइल सहेजी गई!',
    worker_profile:'मजदूर प्रोफ़ाइल', language_voice:'भाषा और आवाज़',
    activity:'गतिविधि', interface_language:'इंटरफ़ेस भाषा', active:'सक्रिय',
    voice_input:'आवाज़ इनपुट', text_to_speech:'पाठ से आवाज़',
    play_sample:'नमूना चलाएं', member_since:'सदस्य से',
    need_help:'और मदद चाहिए?', kisan_helpline:'किसान कॉल सेंटर',
    analysing:'विश्लेषण हो रहा है…',
  },

  kn: {
    dashboard:'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್', jobs:'ಕೆಲಸ', workers:'ಕಾರ್ಮಿಕರು', live_tracking:'ನೇರ ಟ್ರ್ಯಾಕಿಂಗ್',
    equipment:'ಉಪಕರಣ', marketplace:'ಮಾರ್ಕೆಟ್', ai_advisory:'AI ಸಲಹೆ',
    calendar:'ಕ್ಯಾಲೆಂಡರ್', schemes:'ಯೋಜನೆಗಳು', market_prices:'ಮಾರುಕಟ್ಟೆ ಬೆಲೆ',
    community:'ಸಮುದಾಯ', payments:'ಪಾವತಿ', profile:'ಪ್ರೊಫೈಲ್', sign_out:'ಸೈನ್ ಔಟ್',
    good_morning:'ಶುಭೋದಯ', good_afternoon:'ನಮಸ್ಕಾರ', good_evening:'ಶುಭ ಸಂಜೆ',
    farmer:'ರೈತ', worker:'ಕಾರ್ಮಿಕ', admin:'ನಿರ್ವಾಹಕ',
    open_jobs:'ತೆರೆದ ಕೆಲಸಗಳು', available_workers:'ಲಭ್ಯ ಕಾರ್ಮಿಕರು',
    platform_overview:'ವೇದಿಕೆಯ ನೋಟ', live_numbers:'ಭಾರತದ ಲೈವ್ ಸಂಖ್ಯೆಗಳು',
    quick_access:'ತ್ವರಿತ ಪ್ರವೇಶ', recent_jobs:'ಇತ್ತೀಚಿನ ಕೆಲಸಗಳು',
    farm_schedule:'ತೋಟದ ಕಾರ್ಯಕ್ರಮ', community_posts:'ಸಮುದಾಯ',
    view_all:'ಎಲ್ಲಾ ನೋಡಿ', add_event:'+ ಘಟನೆ ಸೇರಿಸಿ', share_tip:'ಸಲಹೆ ಹಂಚಿ',
    no_jobs:'ತೆರೆದ ಕೆಲಸಗಳಿಲ್ಲ', no_events:'ಇನ್ನೂ ಯಾವ ಘಟನೆಗಳಿಲ್ಲ',
    no_posts:'ಇನ್ನೂ ಯಾವ ಪೋಸ್ಟ್‌ಗಳಿಲ್ಲ', schedule_now:'ಈಗ ನಿಗದಿ ಮಾಡಿ',
    total_spent:'ಒಟ್ಟು ಖರ್ಚು', jobs_posted:'ಕೆಲಸ ಪೋಸ್ಟ್', applications:'ಅರ್ಜಿಗಳು',
    equipment_booked:'ಉಪಕರಣ ಬುಕ್', jobs_applied:'ಕೆಲಸಕ್ಕೆ ಅರ್ಜಿ',
    accepted:'ಅಂಗೀಕರಿಸಲಾಗಿದೆ', earned:'ಗಳಿಕೆ', rating:'ರೇಟಿಂಗ್',
    live_weather:'ನೇರ ಹವಾಮಾನ', todays_farm_advisory:'ಇಂದಿನ ಕೃಷಿ ಸಲಹೆ',
    day_forecast:'5 ದಿನ ಮುನ್ಸೂಚನೆ', seed_prices:'ಬೀಜ ಮತ್ತು ಸರಕು ಬೆಲೆಗಳು',
    india_msp:'ಭಾರತ MSP', global:'ಜಾಗತಿಕ', feels_like:'ಅನಿಸಿಕೆ',
    humidity:'ತೇವಾಂಶ', wind:'ಗಾಳಿ', rain:'ಮಳೆ',
    post_job:'ಕೆಲಸ ಪೋಸ್ಟ್ ಮಾಡಿ', apply_now:'ಈಗ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
    job_type:'ಕೆಲಸದ ಪ್ರಕಾರ', all_types:'ಎಲ್ಲಾ ಪ್ರಕಾರ', all_states:'ಎಲ್ಲಾ ರಾಜ್ಯಗಳು',
    search_jobs:'ಕೆಲಸ ಹುಡುಕಿ…', workers_needed:'ಬೇಕಾದ ಕಾರ್ಮಿಕರು',
    wage_per_day:'ದಿನದ ವೇತನ (₹)', start_date:'ಪ್ರಾರಂಭ ದಿನಾಂಕ', end_date:'ಅಂತ್ಯ ದಿನಾಂಕ',
    description:'ವಿವರಣೆ', location:'ಸ್ಥಳ', state:'ರಾಜ್ಯ', season:'ಋತು',
    job_title:'ಕೆಲಸದ ಶೀರ್ಷಿಕೆ', post_job_btn:'ಕೆಲಸ ಪೋಸ್ಟ್ ಮಾಡಿ',
    cancel:'ರದ್ದು ಮಾಡಿ', posting:'ಪೋಸ್ಟ್ ಆಗುತ್ತಿದೆ…',
    days_left:'ದಿನ ಬಾಕಿ', last_day:'ಕೊನೆಯ ದಿನ', ai_wage:'AI ನ್ಯಾಯ ವೇತನ ಸಲಹೆ',
    wage_range:'ಶ್ರೇಣಿ', loading_jobs:'ಕೆಲಸಗಳನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ…',
    no_jobs_found:'ಯಾವ ಕೆಲಸಗಳೂ ಕಂಡುಬಂದಿಲ್ಲ',
    available:'ಲಭ್ಯವಿದೆ', unavailable:'ಲಭ್ಯವಿಲ್ಲ', contact:'ಸಂಪರ್ಕ',
    exp_years:'ವರ್ಷ ಅನುಭವ', all_workers:'ಎಲ್ಲಾ ಕಾರ್ಮಿಕರು', available_only:'ಲಭ್ಯ ಮಾತ್ರ',
    all_skills:'ಎಲ್ಲಾ ಕೌಶಲ್ಯ', my_profile:'ನನ್ನ ಪ್ರೊಫೈಲ್', save_profile:'ಪ್ರೊಫೈಲ್ ಉಳಿಸಿ',
    skills:'ಕೌಶಲ್ಯಗಳು', experience:'ಅನುಭವ (ವರ್ಷ)', preferred_state:'ಆದ್ಯತೆಯ ರಾಜ್ಯ',
    daily_wage:'ದಿನದ ವೇತನ (₹)', bio:'ಪರಿಚಯ', saving:'ಉಳಿಸಲಾಗುತ್ತಿದೆ…',
    any_state:'ಯಾವ ರಾಜ್ಯವಾದರೂ', availability_status:'ಲಭ್ಯತೆ ಸ್ಥಿತಿ',
    list_equipment:'ಉಪಕರಣ ಪಟ್ಟಿ ಮಾಡಿ', book:'ಬುಕ್ ಮಾಡಿ',
    add_listing:'+ ಪಟ್ಟಿ ಸೇರಿಸಿ', title:'ಶೀರ್ಷಿಕೆ', category:'ವರ್ಗ',
    price:'ಬೆಲೆ', crop_recommendation:'ಬೆಳೆ ಶಿಫಾರಸು', disease_detection:'ರೋಗ ಪತ್ತೆ',
    soil_yield:'ಮಣ್ಣು ಮತ್ತು ಇಳುವರಿ', get_recommendation:'ಬೆಳೆ ಶಿಫಾರಸು ಪಡೆಯಿರಿ',
    analysing:'ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ…',
    recommended_crop:'ಶಿಫಾರಸು ಮಾಡಿದ ಬೆಳೆ', confidence:'ವಿಶ್ವಾಸ', alternatives:'ಪರ್ಯಾಯಗಳು',
    upload_photo:'ಸಸ್ಯದ ಎಲೆಯ ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ', detect_disease:'ರೋಗ ಪತ್ತೆ ಮಾಡಿ',
    detecting:'ಪತ್ತೆ ಆಗುತ್ತಿದೆ…', what_is_this:'ಈ ರೋಗ ಏನು?',
    do_now:'ಈಗಲೇ ಇದನ್ನು ಮಾಡಿ', step_by_step:'ಹಂತ-ಹಂತ ಚಿಕಿತ್ಸೆ',
    recommended_products:'ಶಿಫಾರಸು ಮಾಡಿದ ಉತ್ಪನ್ನಗಳು', prevention:'ಮುಂದಿನ ಋತುವಿನ ತಡೆ',
    predicted_yield:'ಅಂದಾಜು ಇಳುವರಿ', total_production:'ಒಟ್ಟು ಉತ್ಪಾದನೆ',
    soil_profile:'ಮಣ್ಣಿನ ಪ್ರೊಫೈಲ್', fertilizer_rec:'ಗೊಬ್ಬರ ಶಿಫಾರಸು',
    application_schedule:'ಗೊಬ್ಬರ ವೇಳಾಪಟ್ಟಿ', companion_crops:'ಸಹಕಾರಿ ಬೆಳೆಗಳು',
    harvest_tips:'ಕೊಯ್ಲಿನ ಸಲಹೆ', get_analysis:'ಮಣ್ಣು ಮತ್ತು ಇಳುವರಿ ವಿಶ್ಲೇಷಣೆ ಪಡೆಯಿರಿ',
    add_event_title:'ತೋಟ ಘಟನೆ ಸೇರಿಸಿ', event_type:'ಘಟನೆ ಪ್ರಕಾರ',
    event_title:'ಘಟನೆ ಶೀರ್ಷಿಕೆ', date:'ದಿನಾಂಕ', upcoming_events:'ಮುಂಬರುವ ಘಟನೆಗಳು',
    by_type:'ಪ್ರಕಾರದಿಂದ', calendar_view:'ಕ್ಯಾಲೆಂಡರ್', list_view:'ಪಟ್ಟಿ',
    today:'ಇಂದು', tomorrow:'ನಾಳೆ', click_date:'ದಿನಾಂಕ ಕ್ಲಿಕ್ ಮಾಡಿ',
    total_events:'ಒಟ್ಟು ಘಟನೆಗಳು', upcoming:'ಮುಂಬರುವ', done_events:'ಪೂರ್ಣ', next_event:'ಮುಂದಿನ ಘಟನೆ',
    search_posts:'ಪೋಸ್ಟ್ ಹುಡುಕಿ…', newest_first:'ಹೊಸದು ಮೊದಲು', most_liked:'ಹೆಚ್ಚು ಇಷ್ಟಪಟ್ಟ',
    share_post:'+ ಪೋಸ್ಟ್ ಹಂಚಿ', write_post:'ಪೋಸ್ಟ್ ಬರೆಯಿರಿ',
    share_knowledge:'ನಿಮ್ಮ ಜ್ಞಾನ ಹಂಚಿ', trending:'ಟ್ರೆಂಡಿಂಗ್ ವಿಷಯಗಳು',
    post_title:'ಶೀರ್ಷಿಕೆ', your_message:'ನಿಮ್ಮ ಸಲಹೆ', video_link:'ವೀಡಿಯೊ ಲಿಂಕ್ (ಐಚ್ಛಿಕ)',
    publishing:'ಪೋಸ್ಟ್ ಆಗುತ್ತಿದೆ…', publish:'ಪೋಸ್ಟ್ ಮಾಡಿ',
    farming_tip:'ಕೃಷಿ ಸಲಹೆ', disease_alert:'ರೋಗ ಎಚ್ಚರಿಕೆ', govt_scheme:'ಸರ್ಕಾರಿ ಯೋಜನೆ',
    market_update:'ಮಾರ್ಕೆಟ್ ಅಪ್ಡೇಟ್', general:'ಸಾಮಾನ್ಯ', all_posts:'ಎಲ್ಲಾ',
    no_posts_found:'ಯಾವ ಪೋಸ್ಟ್‌ಗಳೂ ಹೊಂದಾಣಿಕೆಯಾಗಿಲ್ಲ.',
    apply:'ಅರ್ಜಿ ಸಲ್ಲಿಸಿ →', no_transactions:'ಯಾವ ವಹಿವಾಟುಗಳಿಲ್ಲ',
    recent_transactions:'ಇತ್ತೀಚಿನ ವಹಿವಾಟುಗಳು', amount:'ಮೊತ್ತ',
    status:'ಸ್ಥಿತಿ', tx_date:'ದಿನಾಂಕ', tx_type:'ಪ್ರಕಾರ',
    personal_info:'ವ್ಯಕ್ತಿಗತ ಮಾಹಿತಿ', full_name:'ಪೂರ್ಣ ಹೆಸರು', phone:'ಫೋನ್ ಸಂಖ್ಯೆ',
    village:'ಗ್ರಾಮ / ಸ್ಥಳ', save_changes:'ಬದಲಾವಣೆ ಉಳಿಸಿ', saved_ok:'✓ ಪ್ರೊಫೈಲ್ ಉಳಿಸಲಾಗಿದೆ!',
    worker_profile:'ಕಾರ್ಮಿಕ ಪ್ರೊಫೈಲ್', language_voice:'ಭಾಷೆ ಮತ್ತು ಧ್ವನಿ',
    activity:'ಚಟುವಟಿಕೆ', interface_language:'ಇಂಟರ್ಫೇಸ್ ಭಾಷೆ', active:'ಸಕ್ರಿಯ',
    voice_input:'ಧ್ವನಿ ಇನ್‌ಪುಟ್', text_to_speech:'ಪಠ್ಯದಿಂದ ಧ್ವನಿ',
    play_sample:'ಮಾದರಿ ಚಾಲಿಸಿ', member_since:'ಸದಸ್ಯರಾಗಿದ್ದಾರೆ',
    need_help:'ಹೆಚ್ಚಿನ ಸಹಾಯ ಬೇಕೇ?', kisan_helpline:'ಕಿಸಾನ್ ಕಾಲ್ ಸೆಂಟರ್',
    notes:'ಟಿಪ್ಪಣಿಗಳು', unit:'ಘಟಕ', stock:'ಸ್ಟಾಕ್',
  },

  te: {
    dashboard:'డాష్‌బోర్డ్', jobs:'పని', workers:'కార్మికులు', live_tracking:'నేరుగా ట్రాకింగ్',
    equipment:'పరికరాలు', marketplace:'మార్కెట్', ai_advisory:'AI సలహా',
    calendar:'క్యాలెండర్', schemes:'పథకాలు', market_prices:'మార్కెట్ ధరలు',
    community:'సమాజం', payments:'చెల్లింపులు', profile:'ప్రొఫైల్', sign_out:'సైన్ అవుట్',
    good_morning:'శుభోదయం', good_afternoon:'నమస్కారం', good_evening:'శుభ సాయంత్రం',
    farmer:'రైతు', worker:'కార్మికుడు', admin:'నిర్వాహకుడు',
    open_jobs:'తెరచిన పనులు', available_workers:'అందుబాటులో కార్మికులు',
    quick_access:'శీఘ్ర ప్రాప్యత', recent_jobs:'ఇటీవలి పనులు',
    view_all:'అన్నీ చూడు', total_spent:'మొత్తం ఖర్చు', jobs_posted:'పోస్ట్ చేసిన పనులు',
    applications:'దరఖాస్తులు', equipment_booked:'బుక్ చేసిన పరికరాలు',
    available:'అందుబాటులో', unavailable:'అందుబాటులో లేదు', contact:'సంప్రదించు',
    post_job:'పని పోస్ట్ చేయండి', apply_now:'ఇప్పుడే దరఖాస్తు', book:'బుక్ చేయండి',
    cancel:'రద్దు చేయండి', 
    save_changes:'మార్పులు సేవ్ చేయండి',all_states:'అన్ని రాష్ట్రాలు',
    today:'నేడు', tomorrow:'రేపు', analysing:'విశ్లేషిస్తున్నాం…',
    skills:'నైపుణ్యాలు', experience:'అనుభవం', daily_wage:'రోజు వేతనం (₹)',
    saving:'సేవ్ అవుతున్నది…', any_state:'ఏదైనా రాష్ట్రం',
    humidity:'తేమ', wind:'గాలి', rain:'వర్షం', live_weather:'నేరుగా వాతావరణం',
    crop_recommendation:'పంట సిఫారసు', disease_detection:'వ్యాధి గుర్తింపు',
    soil_yield:'నేల మరియు దిగుబడి', recommended_crop:'సిఫారసు చేసిన పంట',
    detect_disease:'వ్యాధి గుర్తించు', predicted_yield:'అంచనా దిగుబడి',
    apply:'దరఖాస్తు చేయండి →', no_transactions:'లావాదేవీలు లేవు',
    personal_info:'వ్యక్తిగత సమాచారం', full_name:'పూర్తి పేరు', phone:'ఫోన్ నంబర్',
    village:'గ్రామం / స్థలం', saved_ok:'✓ ప్రొఫైల్ సేవ్ చేయబడింది!',
    need_help:'మరింత సహాయం కావాలా?', kisan_helpline:'కిసాన్ కాల్ సెంటర్',
  },

  ta: {
    dashboard:'டாஷ்போர்டு', jobs:'வேலை', workers:'தொழிலாளர்கள்', live_tracking:'நேரடி கண்காணிப்பு',
    equipment:'உபகரணங்கள்', marketplace:'சந்தை', ai_advisory:'AI ஆலோசனை',
    calendar:'நாட்காட்டி', schemes:'திட்டங்கள்', market_prices:'சந்தை விலைகள்',
    community:'சமூகம்', payments:'கட்டணங்கள்', profile:'சுயவிவரம்', sign_out:'வெளியேறு',
    good_morning:'காலை வணக்கம்', good_afternoon:'வணக்கம்', good_evening:'மாலை வணக்கம்',
    farmer:'விவசாயி', worker:'தொழிலாளி', admin:'நிர்வாகி',
    open_jobs:'திறந்த வேலைகள்', available_workers:'கிடைக்கும் தொழிலாளர்கள்',
    quick_access:'விரைவு அணுகல்', recent_jobs:'சமீபத்திய வேலைகள்',
    view_all:'அனைத்தும் காண்க', post_job:'வேலை பதிவிடுக', apply_now:'இப்போது விண்ணப்பிக்கவும்',
    available:'கிடைக்கும்', unavailable:'கிடைக்காது', contact:'தொடர்பு',
    book:'முன்பதிவு செய்யுங்கள்', cancel:'ரத்து செய்யுங்கள்',
    total_spent:'மொத்த செலவு', jobs_posted:'பதிவிட்ட வேலைகள்',
    applications:'விண்ணப்பங்கள்', skills:'திறமைகள்',
    save_changes:'மாற்றங்களை சேமிக்கவும்', saved_ok:'✓ சுயவிவரம் சேமிக்கப்பட்டது!',
    today:'இன்று', tomorrow:'நாளை', humidity:'ஈரப்பதம்', wind:'காற்று', rain:'மழை',
    live_weather:'நேரடி வானிலை', crop_recommendation:'பயிர் பரிந்துரை',
    disease_detection:'நோய் கண்டறிதல்', soil_yield:'மண் மற்றும் விளைச்சல்',
    recommended_crop:'பரிந்துரைக்கப்பட்ட பயிர்', detect_disease:'நோயை கண்டறி',
    analysing:'பகுப்பாய்வு செய்கிறது…', apply:'விண்ணப்பிக்கவும் →',
    no_transactions:'பரிவர்த்தனைகள் இல்லை', personal_info:'தனிப்பட்ட தகவல்',
    full_name:'முழு பெயர்', phone:'தொலைபேசி எண்', village:'கிராமம் / இடம்',
    need_help:'மேலும் உதவி வேண்டுமா?', kisan_helpline:'கிசான் கால் சென்டர்',
    any_state:'எந்த மாநிலமும்', saving:'சேமிக்கிறது…', all_states:'அனைத்து மாநிலங்கள்',
  },

  mr: {
    dashboard:'डॅशबोर्ड', jobs:'काम', workers:'मजूर', live_tracking:'थेट ट्रॅकिंग',
    equipment:'उपकरणे', marketplace:'बाजार', ai_advisory:'AI सल्ला',
    calendar:'दिनदर्शिका', schemes:'योजना', market_prices:'बाजार भाव',
    community:'समुदाय', payments:'देयके', profile:'प्रोफाईल', sign_out:'साइन आउट',
    good_morning:'सुप्रभात', good_afternoon:'नमस्कार', good_evening:'शुभ संध्या',
    farmer:'शेतकरी', worker:'मजूर', admin:'प्रशासक',
    open_jobs:'उघड्या नोकऱ्या', available_workers:'उपलब्ध मजूर',
    quick_access:'जलद प्रवेश', recent_jobs:'अलीकडील कामे',
    view_all:'सर्व पहा', post_job:'काम पोस्ट करा', apply_now:'आता अर्ज करा',
    available:'उपलब्ध', unavailable:'अनुपलब्ध', contact:'संपर्क', book:'बुक करा',
    cancel:'रद्द करा', total_spent:'एकूण खर्च', jobs_posted:'पोस्ट केलेली कामे',
    applications:'अर्ज', skills:'कौशल्ये', save_changes:'बदल जतन करा',
    saved_ok:'✓ प्रोफाईल जतन झाली!', today:'आज', tomorrow:'उद्या',
    humidity:'आर्द्रता', wind:'वारा', rain:'पाऊस', live_weather:'थेट हवामान',
    crop_recommendation:'पीक शिफारस', disease_detection:'रोग ओळख',
    soil_yield:'माती आणि उत्पन्न', recommended_crop:'शिफारस केलेले पीक',
    detect_disease:'रोग ओळखा', analysing:'विश्लेषण होत आहे…',
    apply:'अर्ज करा →', no_transactions:'व्यवहार नाहीत',
    personal_info:'वैयक्तिक माहिती', full_name:'पूर्ण नाव', phone:'फोन नंबर',
    village:'गाव / ठिकाण', need_help:'आणखी मदत हवी आहे का?',
    kisan_helpline:'किसान कॉल सेंटर', any_state:'कोणतेही राज्य',
    saving:'जतन होत आहे…', all_states:'सर्व राज्ये',
  },

  gu: {
    dashboard:'ડેશબોર્ડ', jobs:'કામ', workers:'મજૂરો', live_tracking:'લાઇવ ટ્રેકિંગ',
    equipment:'સાધનો', marketplace:'બજાર', ai_advisory:'AI સલાહ',
    calendar:'કેલેન્ડર', schemes:'યોજનાઓ', market_prices:'બજાર ભાવ',
    community:'સમુદાય', payments:'ચૂકવણી', profile:'પ્રોફાઇલ', sign_out:'સાઇન આઉટ',
    good_morning:'સુપ્રભાત', good_afternoon:'નમસ્તે', good_evening:'શુભ સાંજ',
    farmer:'ખેડૂત', worker:'મજૂર', available:'ઉપલબ્ધ', unavailable:'અનુપલબ્ધ',
    post_job:'કામ પોસ્ટ કરો', apply_now:'અત્યારે અરજી કરો', book:'બુક કરો',
    cancel:'રદ કરો', save_changes:'ફેરફારો સાચવો', saved_ok:'✓ પ્રોફાઇલ સાચવી!',
    today:'આજ', tomorrow:'કાલ', humidity:'ભેજ', wind:'પવન', rain:'વરસાદ',
    crop_recommendation:'પાક ભલામણ', disease_detection:'રોગ શોધ',
    apply:'અરજી કરો →', any_state:'કોઈ પણ રાજ્ય', saving:'સાચવાઈ રહ્યું…',
    analysing:'વિશ્લેષણ…', need_help:'વધુ મદદ જોઈએ છે?', kisan_helpline:'કિસાન કોલ સેન્ટર',
    all_states:'તમામ રાજ્યો',
  },

  pa: {
    dashboard:'ਡੈਸ਼ਬੋਰਡ', jobs:'ਕੰਮ', workers:'ਮਜ਼ਦੂਰ', live_tracking:'ਲਾਈਵ ਟਰੈਕਿੰਗ',
    equipment:'ਉਪਕਰਣ', marketplace:'ਬਾਜ਼ਾਰ', ai_advisory:'AI ਸਲਾਹ',
    calendar:'ਕੈਲੰਡਰ', schemes:'ਯੋਜਨਾਵਾਂ', market_prices:'ਬਾਜ਼ਾਰ ਭਾਅ',
    community:'ਭਾਈਚਾਰਾ', payments:'ਭੁਗਤਾਨ', profile:'ਪ੍ਰੋਫਾਈਲ', sign_out:'ਸਾਈਨ ਆਉਟ',
    good_morning:'ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ', good_afternoon:'ਨਮਸਕਾਰ', good_evening:'ਸ਼ੁਭ ਸ਼ਾਮ',
    farmer:'ਕਿਸਾਨ', worker:'ਮਜ਼ਦੂਰ', available:'ਉਪਲਬਧ', unavailable:'ਉਪਲਬਧ ਨਹੀਂ',
    post_job:'ਕੰਮ ਪੋਸਟ ਕਰੋ', apply_now:'ਹੁਣੇ ਅਰਜ਼ੀ ਕਰੋ', book:'ਬੁੱਕ ਕਰੋ',
    cancel:'ਰੱਦ ਕਰੋ', save_changes:'ਤਬਦੀਲੀਆਂ ਸੇਵ ਕਰੋ', saved_ok:'✓ ਪ੍ਰੋਫਾਈਲ ਸੇਵ ਕੀਤੀ!',
    today:'ਅੱਜ', tomorrow:'ਕੱਲ੍ਹ', humidity:'ਨਮੀ', wind:'ਹਵਾ', rain:'ਬਾਰਿਸ਼',
    crop_recommendation:'ਫਸਲ ਸਿਫਾਰਸ਼', apply:'ਅਰਜ਼ੀ ਕਰੋ →',
    any_state:'ਕੋਈ ਵੀ ਰਾਜ', saving:'ਸੇਵ ਹੋ ਰਿਹਾ ਹੈ…',
    analysing:'ਵਿਸ਼ਲੇਸ਼ਣ ਕਰ ਰਿਹਾ ਹੈ…', need_help:'ਹੋਰ ਮਦਦ ਚਾਹੀਦੀ ਹੈ?',
    kisan_helpline:'ਕਿਸਾਨ ਕਾਲ ਸੈਂਟਰ', all_states:'ਸਾਰੇ ਰਾਜ',
  },

  bn: {
    dashboard:'ড্যাশবোর্ড', jobs:'কাজ', workers:'শ্রমিক', live_tracking:'লাইভ ট্র্যাকিং',
    equipment:'সরঞ্জাম', marketplace:'বাজার', ai_advisory:'AI পরামর্শ',
    calendar:'ক্যালেন্ডার', schemes:'প্রকল্প', market_prices:'বাজার মূল্য',
    community:'সম্প্রদায়', payments:'পেমেন্ট', profile:'প্রোফাইল', sign_out:'সাইন আউট',
    good_morning:'শুভ সকাল', good_afternoon:'নমস্কার', good_evening:'শুভ সন্ধ্যা',
    farmer:'কৃষক', worker:'শ্রমিক', available:'উপলব্ধ', unavailable:'অনুপলব্ধ',
    post_job:'কাজ পোস্ট করুন', apply_now:'এখনই আবেদন করুন', book:'বুক করুন',
    cancel:'বাতিল করুন', save_changes:'পরিবর্তন সংরক্ষণ', saved_ok:'✓ প্রোফাইল সংরক্ষিত!',
    today:'আজ', tomorrow:'আগামীকাল', humidity:'আর্দ্রতা', wind:'বায়ু', rain:'বৃষ্টি',
    crop_recommendation:'ফসল সুপারিশ', apply:'আবেদন করুন →',
    any_state:'যেকোনো রাজ্য', saving:'সংরক্ষণ হচ্ছে…',
    analysing:'বিশ্লেষণ হচ্ছে…', need_help:'আরও সাহায্য দরকার?',
    kisan_helpline:'কিসান কল সেন্টার', all_states:'সব রাজ্য',
  },
}

// ── Language Context ────────────────────────────────────────────────────────────
const LangContext = createContext(null)

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('shramic_lang') || 'en')

  const changeLang = (code) => {
    setLang(code)
    localStorage.setItem('shramic_lang', code)
    // Update html lang attribute for accessibility
    document.documentElement.lang = code
  }

  const t = (key) => T[lang]?.[key] ?? T.en?.[key] ?? key

  useEffect(() => {
    document.documentElement.lang = lang
  }, [lang])

  return (
    <LangContext.Provider value={{ lang, changeLang, t }}>
      {children}
    </LangContext.Provider>
  )
}

export function useLang() {
  const ctx = useContext(LangContext)
  if (!ctx) throw new Error('useLang must be used inside LangProvider')
  return ctx
}

export const LANGUAGES = [
  { code:'en', label:'English',  native:'English',   flag:'🇬🇧' },
  { code:'hi', label:'Hindi',    native:'हिंदी',      flag:'🇮🇳' },
  { code:'kn', label:'Kannada',  native:'ಕನ್ನಡ',      flag:'🇮🇳' },
  { code:'te', label:'Telugu',   native:'తెలుగు',     flag:'🇮🇳' },
  { code:'ta', label:'Tamil',    native:'தமிழ்',      flag:'🇮🇳' },
  { code:'mr', label:'Marathi',  native:'मराठी',      flag:'🇮🇳' },
  { code:'gu', label:'Gujarati', native:'ગુજરાતી',    flag:'🇮🇳' },
  { code:'pa', label:'Punjabi',  native:'ਪੰਜਾਬੀ',     flag:'🇮🇳' },
  { code:'bn', label:'Bengali',  native:'বাংলা',      flag:'🇮🇳' },
]